In [45]:
import numpy as np

```
1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
```

In [46]:
a = np.arange(12, 24)
a.size

12

```
2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
```

In [47]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [48]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [49]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [51]:
a.reshape(-1, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

```
3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).
```

In [52]:
a.reshape((2, -1))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [53]:
a.reshape((6, -1))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [54]:
a.reshape((3, -1))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [55]:
a.reshape((-1, 4))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [56]:
a.reshape((-1, 1))

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

```
4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
```

Ответ: нет, так как атрибут ndim такого массива равен 2, то есть это двумерный массив:

In [57]:
b = a.reshape(12, 1)
b.ndim

2

```
5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения 
со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
```

In [89]:
a = np.random.randn(3000, 4000)
a.mean()

-0.00024141351253715652

In [90]:
b = a.flatten()
b

array([ 1.57921282,  0.76743473, -0.46947439, ...,  0.55501375,
       -0.30011844, -3.15670715])

In [95]:
a.ndim

2

In [92]:
a.size

12000000

In [93]:
b.size

12000000

In [94]:
a.size == b.size

True

```
6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
В чем разница между массивами a и b?
```

In [98]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [96]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [99]:
a.shape

(10,)

In [100]:
b.shape

(1, 10)

In [101]:
a.ndim

1

In [102]:
b.ndim

2

```
7. Вертикально соединить массивы a и b. a - двумерный массив из нулей, 
число строк которого больше 1 и на 1 меньше, чем число строк двумерного 
массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.
```

```
Ответ: при вертикальном соединении двумерных массивов получится двумерный массив v.
Возможны 4 варианта значений атрибута shape массива v (исходя из v.size, равного 10):
    1. 1 строка, 10 столбцов
    2. 10 строк, 1 столбец
    3. 2 строки, 5 столбцов
    4. 5 строк, 2 столбца
1 и 3 варианты не подходят, так как у массива а число строк больше 1, 
а у массива b число строк должно быть больше 2 (так у него число строк больше на единицу, чем у a).
При вертикальном их соединении должно получиться не менее 5 строк.
2 вариант не подходит, так как число строк, равное 10 получится, 
только если сложить два четных или два нечетных числа строк, что противоречит условию.
4 вариант подходит, так число 5 можно получить как 2 + 3.
Значит, в массиве a 2 строки, а в массиве b - 3.
Так как итоговый массив при вертикальном соединении должен иметь такое же количество столбцов,
что и исходные массивы, то число столбцов массивов a и b должно равняться 2.
```

In [103]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [104]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Соединим массивы a и b  с помощью функции numpy.vstack:

In [105]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Либо с помощью функции numpy.concatenate, примененной к нулевой оси (строковая ось):

In [106]:
v = np.concatenate((a, b), axis = 0)
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

```
8. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 
4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B?
Получится ли вычислить обратную матрицу для матрицы B и почему?
```

In [107]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [108]:
A = a.reshape((4, 3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [109]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [110]:
B = np.dot(A, At)
print(A.dot(At),"\n",B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]] 
 [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [111]:
np.linalg.det(B)

0.0

```
9. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42. 
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C.
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.
```

In [114]:
np.random.seed(42)
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [115]:
C = c.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [116]:
D = B + C
D

array([[ 11,  17,  35,  46],
       [ 24,  57,  98, 126],
       [ 29,  95, 151, 218],
       [ 42, 132, 219, 306]])

In [117]:
np.linalg.det(D)

-47196.000000000335

In [118]:
np.linalg.matrix_rank(D)

4

In [119]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.13488431,  0.07958302,  0.17988813, -0.1812018 ],
       [-0.17149758,  0.14009662,  0.147343  , -0.13687601],
       [-0.05758963,  0.01220442, -0.20404272,  0.14899568],
       [ 0.09668192, -0.08009153,  0.05778032, -0.0194508 ]])

```
10. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
Убедитесь, что в матрице D_inv остались только нули и единицы.
С помощью функции numpy.where, используя матрицу D_inv в качестве маски,
а матрицы B и C - в качестве источников данных,
получите матрицу E размером 4x4. 
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1,
должны быть равны соответствующему элементу матрицы B,
а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0,
должны быть равны соответствующему элементу матрицы C.
```

In [120]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [121]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [122]:
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [123]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,  50,  86,   4],
       [  6,  86,   2, 212],
       [ 32,  10, 212,   4]])